title: Igor Savochkin
description: Software Engineer | Researcher
email: savochkin@physics.msu.ru
github_username: neonh

# Build settings
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
